Repository kdelay/TDD-Study, pull requests merged in 2024-05, with the labels that each got.

#3 [240503] 01, 02 - JUnit 설치 및 tdd 예제 풀이
  kdelay/chapter01/TDD_개발_준비/JUnit5_설치.md
  kdelay/chapter01/TDD_개발_준비/테스트_실행결과.png
  kdelay/chapter02/TDD_시작/덧셈기능.md
  kdelay/chapter02/TDD_시작/암호검사기.md
Labels: documentation

#18 [240506] #9 [챕터 1, 2] - 문제
  study/chapter01_02/img.png
  study/chapter01_02/답안.md
  study/chapter01_02/문제.md
Labels: weekly

#16 [240506] gitignore 추가
  .gitignore
Labels: setting

#21 [240509] 03. 유료 서비스 TDD 작성 #19
  kdelay/gradle/src/test/java/com/tdd/chapter03/ExpiryDateCalculator.java
  kdelay/gradle/src/test/java/com/tdd/chapter03/ExpiryDateCalculatorTest.java
  kdelay/gradle/src/test/java/com/tdd/chapter03/PayData.java
Labels: study

#22 [240509] 03, 04 - 문제 및 실습
  study/chapter03_04/답안.md
  study/chapter03_04/문제.md
Labels: weekly

#27 [240512] 03, 04 - 과제 실습 문제 풀이
  kdelay/gradle/build.gradle
  kdelay/gradle/src/main/java/com/tdd/report/Billing.java
  kdelay/gradle/src/main/java/com/tdd/report/BillingUtils.java
  kdelay/gradle/src/main/java/com/tdd/report/PaymentMethod.java
  kdelay/gradle/src/test/java/com/tdd/report/reportTest.java
  kdelay/report/chapter03_04.md
Labels: weekly

#26 3강정리
  RealWarm/tdd/src/main/java/com/study/tdd/chap03/ExpiryDateCalculator.java
  RealWarm/tdd/src/main/java/com/study/tdd/chap03/PayData.java
  RealWarm/tdd/src/test/java/com/study/tdd/chap03/ExpiryDateCalculatorTest.java
Labels: study

#33 [240518] 07. 대역
  kdelay/chapter07/대역/대역.md
  kdelay/gradle/build.gradle
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/domain/AutoDebitInfo.java
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/domain/AutoDebitReq.java
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/repository/AutoDebitInfoRepository.java
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/repository/MemoryAutoDebitInfoRepository.java
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/service/AutoDebitRegister.java
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/service/RegisterResult.java
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/validate/CardNumberValidator.java
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/validate/CardValidity.java
  kdelay/gradle/src/main/java/com/tdd/chapter07/autodebit/validate/StubCardNumberValidator.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/autodebit/AutoDebitRegister_Fake_Test.java
  kdelay/gradle/src/test/java/com/tdd/report/Billing.java
  kdelay/gradle/src/test/java/com/tdd/report/BillingUtils.java
  kdelay/gradle/src/test/java/com/tdd/report/PaymentMethod.java
Labels: study

#35 [240518] 부록C. Mockito
  kdelay/gradle/build.gradle
  kdelay/gradle/src/test/java/com/tdd/addition/mockito/Game.java
  kdelay/gradle/src/test/java/com/tdd/addition/mockito/GameGenMockTest.java
  kdelay/gradle/src/test/java/com/tdd/addition/mockito/GameLevel.java
  kdelay/gradle/src/test/java/com/tdd/addition/mockito/GameNumGen.java
Labels: study

#36 [240519] 07. 모의 객체 사용 #32
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/UserRegisterMockTest.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/UserRegisterTest.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/domain/User.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/exception/DupIdException.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/exception/WeakPasswordException.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/repository/MemoryUserRepository.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/repository/UserRepository.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/service/UserRegister.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/validation/EmailNotifier.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/validation/SpyEmailNotifier.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/validation/StubWeakPasswordChecker.java
  kdelay/gradle/src/test/java/com/tdd/chapter07/user/validation/WeakPasswordChecker.java
Labels: study

#39 [240519] 05, 06, 07 - 과제 문제 풀이
  kdelay/report/chapter05_06_07.md
Labels: weekly

#40 [240524] Mockist 정리
  kdelay/chapter07/대역/mockist.md
Labels: study

#42 [240525] #41 [챕터 7, 8, 9, 부록 C] - 문제
  study/chapter07_C_08_09/img.png
  study/chapter07_C_08_09/답안.md
  study/chapter07_C_08_09/문제.md
Labels: weekly
